# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.0.0"
  python_check_max: "3.14"

package:
  name: send2trash
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/send2trash/send2trash-${{ version }}.tar.gz
  sha256: 1761421da3f9930bfe51ed7c45343948573383ad4c27e3acebc91be324e7770d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - send2trash = send2trash.__main__:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=75.3.1
  run:
    - __${{ noarch_platform }}
    - ${{ "pyobjc-framework-cocoa"  if noarch_platform == "osx" }}
    - ${{ "pywin32"                 if noarch_platform == "win" }}
    - python >=${{ python_min }}

tests:
  - python:
      imports: send2trash
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}
    script:
      - send2trash -h
      - coverage run --source=send2trash --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=37

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python library to natively send files to Trash (or Recycle bin) on all platforms.
  homepage: https://pypi.org/project/send2trash
  repository: https://github.com/arsenetar/send2trash

extra:
  recipe-maintainers:
    - bollwyvl
